In [1]:
import torch

In [2]:
a = torch.arange(20)  # 生成0~19的向量
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [3]:
a.shape,a.numel()  # 张量形状，元素个数

(torch.Size([20]), 20)

In [4]:
a = a.reshape(4,5)
a

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [5]:
b = torch.zeros(4,5)
c = torch.ones(4,5)
b,c

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]))

In [6]:
d = torch.tensor([[3,3],[7,8],[4,5],[8,1],[8,0]])
d,d.shape

(tensor([[3, 3],
         [7, 8],
         [4, 5],
         [8, 1],
         [8, 0]]),
 torch.Size([5, 2]))

In [7]:
a+b,a-c,a*b,a/c

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[-1.,  0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12., 13.],
         [14., 15., 16., 17., 18.]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]))

In [8]:
torch.exp(a)  # torch.exp -> e^a

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03],
        [2.2026e+04, 5.9874e+04, 1.6275e+05, 4.4241e+05, 1.2026e+06],
        [3.2690e+06, 8.8861e+06, 2.4155e+07, 6.5660e+07, 1.7848e+08]])

In [9]:
torch.cat((a,b),dim=0),torch.cat((a,b),dim=1)  # 张量的连接：torch.cat((张量一，张量二)，dim=连接改变的维度)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.,  0.,  0.,  0.,  0.,  0.],
         [ 5.,  6.,  7.,  8.,  9.,  0.,  0.,  0.,  0.,  0.],
         [10., 11., 12., 13., 14.,  0.,  0.,  0.,  0.,  0.],
         [15., 16., 17., 18., 19.,  0.,  0.,  0.,  0.,  0.]]))

In [10]:
a == b  # 逻辑运算

tensor([[ True, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [11]:
a.sum()  # 对张量所有元素求和会生成一个元素的张量

tensor(190)

In [12]:
e = torch.tensor([[0],[1],[2]])
f = torch.tensor([[0,1]])
g = torch.tensor([[0,0],[1,1],[2,2]])
h = torch.tensor([[0,1],[0,1],[0,1]])
e,f,e + f
#  广播机制：形状不同的张量进行运算，先将元素复制成相同形状再运算

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [13]:
# 效果同上
g = torch.tensor([[0,0],[1,1],[2,2]])
h = torch.tensor([[0,1],[0,1],[0,1]])
g,h,g + h

(tensor([[0, 0],
         [1, 1],
         [2, 2]]),
 tensor([[0, 1],
         [0, 1],
         [0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [14]:
a,a[-1],a[2:4],a[2,3:5]  # 简单切片(左闭右开)

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([15, 16, 17, 18, 19]),
 tensor([[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([13, 14]))

In [15]:
a = torch.arange(20).reshape(4,5)
a[:,2:3] = 0
a  # 通过索引改变张量指定元素

tensor([[ 0,  1,  0,  3,  4],
        [ 5,  6,  0,  8,  9],
        [10, 11,  0, 13, 14],
        [15, 16,  0, 18, 19]])

In [16]:
before = id(a)  # id():类似获取a的指针的操作
a = a + b  # 此步为a分配了新的内存(本质上产生了一个新的a)
id(a) == before,before,id(a)

(False, 2879408626560, 2879408598928)

In [17]:
# 执行原地操作（避免出现上述问题）
i = torch.zeros_like(a)  # 生成形如a的零张量
before = id(i)
i[:] = a + b  # 改变i张量内所有元素（本质上是对i各元素赋值）
id(i) == before,before,id(i)

(True, 2879408473408, 2879408473408)

In [18]:
# 效果同上
before = id(a)
a += b  # 区别于a=a+b对整个张量操作（本质上是对a各元素赋值）
id(a) == before,before,id(a)

(True, 2879408598928, 2879408598928)

In [19]:
# 转换为numpy张量
A = a.numpy()
B = torch.tensor(A)
A,B,type(A),type(B)

(array([[ 0.,  1.,  0.,  3.,  4.],
        [ 5.,  6.,  0.,  8.,  9.],
        [10., 11.,  0., 13., 14.],
        [15., 16.,  0., 18., 19.]], dtype=float32),
 tensor([[ 0.,  1.,  0.,  3.,  4.],
         [ 5.,  6.,  0.,  8.,  9.],
         [10., 11.,  0., 13., 14.],
         [15., 16.,  0., 18., 19.]]),
 numpy.ndarray,
 torch.Tensor)

In [20]:
# 将大小为1的张量转换为Python标量
a = torch.tensor([1.0])
a,a.item(),float(a),int(a)

(tensor([1.]), 1.0, 1.0, 1)