In [1]:
import torch

# 标量由只有一个元素的张量表示
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
# 通过一维张量表示向量
x = torch.arange(4)
x,x[1],len(x),x.shape

(tensor([0, 1, 2, 3]), tensor(1), 4, torch.Size([4]))

In [3]:
# 矩阵表示为具有两个轴的张量
A = torch.arange(20).reshape(5, 4)
A,A.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [4]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B,B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]))

In [5]:
# 张量是描述具有任意数量轴的维数组的通用方法
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [6]:
# 张量算法的基本性质
# 1.任何按元素的一元运算都不会改变其操作数的形状
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B, A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [7]:
# 将张量乘以或加上一个标量不会改变张量的形状，
# 其中张量的每个元素都将与标量相加或相乘
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [8]:
# 降维
x = torch.arange(4, dtype=torch.float32)
# 计算各元素总和
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [9]:
# 可以指定张量沿哪一个轴来通过求和降低维度
# （对哪个维度，哪个维度就消失）
A_sum_axis0 = A.sum(axis=0)
A_sum_axis1 = A.sum(axis=1)
A_sum_axis0, A_sum_axis0.shape,A_sum_axis1, A_sum_axis1.shape

(tensor([40., 45., 50., 55.]),
 torch.Size([4]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

In [10]:
A.sum(axis=[0, 1])  # 结果和A.sum()相同

tensor(190.)

In [11]:
# 通过调用函数（.sum()）或将总和除以元素总数来计算平均值
# 计算平均值的函数也可以沿指定轴降低张量的维度
A.mean(), A.sum() / A.numel(),A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor(9.5000),
 tensor(9.5000),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]))

In [12]:
# 非降维求和（keepdims=True来保持轴数/维度不变）
sum_A = A.sum(axis=1, keepdims=True)
# 求和后仍保持两个轴，我们可以通过广播将A除以sum_A
sum_A,A / sum_A

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]))

In [13]:
# 沿某个轴（维度0）计算A元素的累积总和
A.cumsum(axis=0)
# 维度0的累积总和就是第一行不变，第二行变为1+2，第三行1+2+3，以此类推

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [14]:
# 点积（dot product）01是相同位置的按元素乘积的和
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)
# 点积可用于计算矩阵A，B的内积
# 当权重为非负数且和为1，点积表示加权平均
# 将两个向量规范化得到单位长度后，点积表示它们夹角的余弦

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [15]:
# 矩阵的向量积：结果的第n个元素是矩阵A的第n行与向量x的点积
# mv全称Matrix-Vector Multiplication
A,x,A.shape, x.shape, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [16]:
# 矩阵乘法
# mm全称Matrix-Matrix Multiplication
B = torch.ones(4, 3)
A,B,torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [17]:
# 范数 
# L1范数：向量元素绝对值之和；
# L2范数：向量元素平方和的平方根；
# Frobenius范数是矩阵元素平方和的平方根；
u = torch.tensor([3.0, -4.0])
torch.abs(u).sum(),torch.norm(u),torch.norm(torch.ones((4,9)))
# 输出依次为：
# 向量u的L1范数，向量u的L2范数，4*5的单位矩阵的Frobenius范数

(tensor(7.), tensor(5.), tensor(6.))

In [18]:
# 练习1
A,A.T,A.T.T

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  4.,  8., 12., 16.],
         [ 1.,  5.,  9., 13., 17.],
         [ 2.,  6., 10., 14., 18.],
         [ 3.,  7., 11., 15., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [19]:
# 练习2
C = torch.arange(20).reshape(5,4)
(A+C).T,A.T+C.T

(tensor([[ 0.,  8., 16., 24., 32.],
         [ 2., 10., 18., 26., 34.],
         [ 4., 12., 20., 28., 36.],
         [ 6., 14., 22., 30., 38.]]),
 tensor([[ 0.,  8., 16., 24., 32.],
         [ 2., 10., 18., 26., 34.],
         [ 4., 12., 20., 28., 36.],
         [ 6., 14., 22., 30., 38.]]))

In [20]:
A,len(A) #len()输出矩阵的第一维长度

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 5)

In [21]:
# 运行A/A.sum(axis=1)，看看会发生什么。请分析一下原因？
A,A.sum(axis=1) # 两者维度不同无法相除

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]))

In [22]:
X.sum(axis=0),X.sum(axis=1),X.sum(axis=2)

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))